name: run-tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/api'
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --filter=api...

      - name: Run Jest API tests
        run: cd apps/api && pnpm run test:unit
