name: Lint API Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  paths:
#    - 'apps/api'
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/run-linter.template.yml
    with:
      dir: apps/api